In [7]:
a = [1, 2, 3, [2, 3, 4], 5]
print(a[3][1])

3


In [8]:
import numpy as np
lst = [[1,2,3], [4, 5, 6]]
aryld = np.array(lst)
aryld
np.zeros(3)
np.ones(3)




array([1., 1., 1.])

In [12]:
import numpy as np
lst0 = np.zeros(3)
lst1 = np.ones(3)
print(lst0)
print(lst1)

[0. 0. 0.]
[1. 1. 1.]
